//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FoxScan.foxWebSvc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IFoxSvcSql", Namespace="http://tempuri.org/")]
    public partial class FoxSvcSql : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback XMLDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback JSONDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoreNameFromCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoreEmployeeNameFromNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDatasetXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVendorListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategoryListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVersionNumOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FoxSvcSql() {
            this.Url = "http://www.foxsqlsvc.com.foxs.info/FoxSvcSql.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event XMLDataCompletedEventHandler XMLDataCompleted;
        
        /// <remarks/>
        public event JSONDataCompletedEventHandler JSONDataCompleted;
        
        /// <remarks/>
        public event GetStoreNameFromCodeCompletedEventHandler GetStoreNameFromCodeCompleted;
        
        /// <remarks/>
        public event GetStoreEmployeeNameFromNumCompletedEventHandler GetStoreEmployeeNameFromNumCompleted;
        
        /// <remarks/>
        public event GetDatasetXMLCompletedEventHandler GetDatasetXMLCompleted;
        
        /// <remarks/>
        public event GetVendorListCompletedEventHandler GetVendorListCompleted;
        
        /// <remarks/>
        public event GetCategoryListCompletedEventHandler GetCategoryListCompleted;
        
        /// <remarks/>
        public event GetVersionNumCompletedEventHandler GetVersionNumCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFoxSvcSql/XMLData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string XMLData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("XMLData", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XMLDataAsync(string id) {
            this.XMLDataAsync(id, null);
        }
        
        /// <remarks/>
        public void XMLDataAsync(string id, object userState) {
            if ((this.XMLDataOperationCompleted == null)) {
                this.XMLDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXMLDataOperationCompleted);
            }
            this.InvokeAsync("XMLData", new object[] {
                        id}, this.XMLDataOperationCompleted, userState);
        }
        
        private void OnXMLDataOperationCompleted(object arg) {
            if ((this.XMLDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XMLDataCompleted(this, new XMLDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFoxSvcSql/JSONData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string JSONData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("JSONData", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void JSONDataAsync(string id) {
            this.JSONDataAsync(id, null);
        }
        
        /// <remarks/>
        public void JSONDataAsync(string id, object userState) {
            if ((this.JSONDataOperationCompleted == null)) {
                this.JSONDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJSONDataOperationCompleted);
            }
            this.InvokeAsync("JSONData", new object[] {
                        id}, this.JSONDataOperationCompleted, userState);
        }
        
        private void OnJSONDataOperationCompleted(object arg) {
            if ((this.JSONDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JSONDataCompleted(this, new JSONDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFoxSvcSql/GetStoreNameFromCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetStoreNameFromCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _StoreCode) {
            object[] results = this.Invoke("GetStoreNameFromCode", new object[] {
                        _StoreCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStoreNameFromCodeAsync(string _StoreCode) {
            this.GetStoreNameFromCodeAsync(_StoreCode, null);
        }
        
        /// <remarks/>
        public void GetStoreNameFromCodeAsync(string _StoreCode, object userState) {
            if ((this.GetStoreNameFromCodeOperationCompleted == null)) {
                this.GetStoreNameFromCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoreNameFromCodeOperationCompleted);
            }
            this.InvokeAsync("GetStoreNameFromCode", new object[] {
                        _StoreCode}, this.GetStoreNameFromCodeOperationCompleted, userState);
        }
        
        private void OnGetStoreNameFromCodeOperationCompleted(object arg) {
            if ((this.GetStoreNameFromCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoreNameFromCodeCompleted(this, new GetStoreNameFromCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFoxSvcSql/GetStoreEmployeeNameFromNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetStoreEmployeeNameFromNum([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _empNum) {
            object[] results = this.Invoke("GetStoreEmployeeNameFromNum", new object[] {
                        _empNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStoreEmployeeNameFromNumAsync(string _empNum) {
            this.GetStoreEmployeeNameFromNumAsync(_empNum, null);
        }
        
        /// <remarks/>
        public void GetStoreEmployeeNameFromNumAsync(string _empNum, object userState) {
            if ((this.GetStoreEmployeeNameFromNumOperationCompleted == null)) {
                this.GetStoreEmployeeNameFromNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoreEmployeeNameFromNumOperationCompleted);
            }
            this.InvokeAsync("GetStoreEmployeeNameFromNum", new object[] {
                        _empNum}, this.GetStoreEmployeeNameFromNumOperationCompleted, userState);
        }
        
        private void OnGetStoreEmployeeNameFromNumOperationCompleted(object arg) {
            if ((this.GetStoreEmployeeNameFromNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoreEmployeeNameFromNumCompleted(this, new GetStoreEmployeeNameFromNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFoxSvcSql/GetDatasetXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDatasetXML([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _sql, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _database, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _serverIP) {
            object[] results = this.Invoke("GetDatasetXML", new object[] {
                        _sql,
                        _database,
                        _serverIP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDatasetXMLAsync(string _sql, string _database, string _serverIP) {
            this.GetDatasetXMLAsync(_sql, _database, _serverIP, null);
        }
        
        /// <remarks/>
        public void GetDatasetXMLAsync(string _sql, string _database, string _serverIP, object userState) {
            if ((this.GetDatasetXMLOperationCompleted == null)) {
                this.GetDatasetXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDatasetXMLOperationCompleted);
            }
            this.InvokeAsync("GetDatasetXML", new object[] {
                        _sql,
                        _database,
                        _serverIP}, this.GetDatasetXMLOperationCompleted, userState);
        }
        
        private void OnGetDatasetXMLOperationCompleted(object arg) {
            if ((this.GetDatasetXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDatasetXMLCompleted(this, new GetDatasetXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFoxSvcSql/GetVendorList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetVendorList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _serverIP) {
            object[] results = this.Invoke("GetVendorList", new object[] {
                        _serverIP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVendorListAsync(string _serverIP) {
            this.GetVendorListAsync(_serverIP, null);
        }
        
        /// <remarks/>
        public void GetVendorListAsync(string _serverIP, object userState) {
            if ((this.GetVendorListOperationCompleted == null)) {
                this.GetVendorListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVendorListOperationCompleted);
            }
            this.InvokeAsync("GetVendorList", new object[] {
                        _serverIP}, this.GetVendorListOperationCompleted, userState);
        }
        
        private void OnGetVendorListOperationCompleted(object arg) {
            if ((this.GetVendorListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVendorListCompleted(this, new GetVendorListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFoxSvcSql/GetCategoryList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetCategoryList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _serverIP) {
            object[] results = this.Invoke("GetCategoryList", new object[] {
                        _serverIP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCategoryListAsync(string _serverIP) {
            this.GetCategoryListAsync(_serverIP, null);
        }
        
        /// <remarks/>
        public void GetCategoryListAsync(string _serverIP, object userState) {
            if ((this.GetCategoryListOperationCompleted == null)) {
                this.GetCategoryListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategoryListOperationCompleted);
            }
            this.InvokeAsync("GetCategoryList", new object[] {
                        _serverIP}, this.GetCategoryListOperationCompleted, userState);
        }
        
        private void OnGetCategoryListOperationCompleted(object arg) {
            if ((this.GetCategoryListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategoryListCompleted(this, new GetCategoryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFoxSvcSql/GetVersionNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetVersionNum(out int GetVersionNumResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GetVersionNumResultSpecified) {
            object[] results = this.Invoke("GetVersionNum", new object[0]);
            GetVersionNumResult = ((int)(results[0]));
            GetVersionNumResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GetVersionNumAsync() {
            this.GetVersionNumAsync(null);
        }
        
        /// <remarks/>
        public void GetVersionNumAsync(object userState) {
            if ((this.GetVersionNumOperationCompleted == null)) {
                this.GetVersionNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVersionNumOperationCompleted);
            }
            this.InvokeAsync("GetVersionNum", new object[0], this.GetVersionNumOperationCompleted, userState);
        }
        
        private void OnGetVersionNumOperationCompleted(object arg) {
            if ((this.GetVersionNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVersionNumCompleted(this, new GetVersionNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void XMLDataCompletedEventHandler(object sender, XMLDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XMLDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XMLDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void JSONDataCompletedEventHandler(object sender, JSONDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JSONDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JSONDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStoreNameFromCodeCompletedEventHandler(object sender, GetStoreNameFromCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoreNameFromCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoreNameFromCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStoreEmployeeNameFromNumCompletedEventHandler(object sender, GetStoreEmployeeNameFromNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoreEmployeeNameFromNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoreEmployeeNameFromNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDatasetXMLCompletedEventHandler(object sender, GetDatasetXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDatasetXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDatasetXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetVendorListCompletedEventHandler(object sender, GetVendorListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVendorListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVendorListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetCategoryListCompletedEventHandler(object sender, GetCategoryListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategoryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategoryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetVersionNumCompletedEventHandler(object sender, GetVersionNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVersionNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVersionNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int GetVersionNumResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GetVersionNumResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591